### ISSUE TITLE
Selection sort and Bubble Sort in C++

### ISSUE THREAD

**Issue by AdityaMore7000** [itsyadavRajkumar/DSA#31]
Dear @itsyadavRajkumar, I would like to contribute to your project by adding the C++ code for selection sort and bubble sort. It can be helpful for solving multiple questions on various coding platforms and also in contests. I will add comments for easy readability and understanding of code.

Please add the hacktoberfest-accepted tag on this issue, and kindly assign it to me. Looking forward to your reply. Thank you

**Comment by akashadr** [comment]
@itsyadavRajkumar  could you plz assign me this issue with hacktoberfest 2022 tag.

**Comment by abhayanand08** [comment]
@itsyadavRajkumar I am very much excited to contribute to this issue . I will solve it with best time complexity. Kindly assign me this task please.

**Comment by Sandyy07** [comment]
Hi @itsyadavRajkumar , Kindly please assign me this issue.

**Comment by manvisaxena14** [comment]
Hello @itsyadavRajkumar, its my first time contributing towards this amazing fest and I want to be a part of your repository for contributing. Please assign me this issue so that I can kickstart my journey towards Open-Source.

**Comment by itsyadavRajkumar** [comment]
done
